### ISSUE TITLE
[FEATURE] User Accounts

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/curse_of_myrra#905]
### Authentication Methods
- DeviceId (unsecured)
- Email & Password
- Google
- Apple Game Center
- Facebook

### Login

The login flow should work as follows:

- 1. Check for any locally saved secure login methods and log-in automatically
- 2. If none is found, check for unsecured accounts with `deviceId`
- 3. If none is found, register a new account and login automatically

Additionally, the user should have a login option in their account settings to swap accounts using one of the Authentication services.

### Registration

The first time a player opens the game, a new account using their `deviceId` should be created. This means that players are ready to play as soon as they load the game, without friction. These accounts should be considered unsecured until the user adds any other authentication method(s). Users will be unable to do any IAP with unsecured accounts.

In a new user account page, the user will then be able to secure their account by linking it to one of the Authentication services mentioned above. Securing your account should clear any linked `deviceId` from the account, preventing logging into it just by owning that device. 

___

### Tasks

- [ ] Implement a UserAccounts entity and database
- [ ] Implement Registration methods as outlined above, for:
  - [ ] DeviceId
  - [ ] Mail/Password (+password recovery)
  - [ ] #60 
  - [ ] Apple Game Center
  - [ ] Facebook
- [ ] Implement Login methods for the selected Authentication services
- [ ] Implement DisplayNames
- [ ] Implement an "Accounts" menu in the frontend with all required functionalities
